### ISSUE TITLE
isFile have bug

### ISSUE THREAD

**Issue by huanghe12** [sor4chi/hono-storage#58] opened 2024-05-23 01:09 UTC
isFile is always false

**Comment by sor4chi** [comment] 2024-05-24 07:06
Hi, @huanghe12 .
Is this problem still unresolved?

Could you tell me your environment of Runtime, OS, etc...?

**Comment by huanghe12** [comment] 2024-05-24 09:40
yes, it's still exits
env is bun of win11

**Comment by sor4chi** [comment] 2024-05-25 10:29
I was able to reproduce it. This seems to be a problem that happens to bun.
I am dealing with it in the form of using File polyfil, but it seems to need to be changed to be implemented with a pure Web File Object.

It may take some time, but I will try.

**Comment by sor4chi** [comment] 2024-06-08 02:45
@huanghe12 This problem will be resolved in the next release! Thank you for rasing this issue!

**Closed** 2024-06-11 14:43 UTC
